package com.day01.bean;

import javax.validation.constraints.Pattern;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.emp_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.emp_name
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    @Pattern(regexp="(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\u9FFF]+$)",message="用户名必须是6-16位英文数字组合或2-5位中文")
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.gender
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.email
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    @Pattern(regexp="^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$",message="邮箱格式不正确")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tab_emp.d_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    private Integer dId;
    
    private Department department;

    public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.emp_id
     *
     * @return the value of tab_emp.emp_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.emp_id
     *
     * @param empId the value for tab_emp.emp_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.emp_name
     *
     * @return the value of tab_emp.emp_name
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.emp_name
     *
     * @param empName the value for tab_emp.emp_name
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.gender
     *
     * @return the value of tab_emp.gender
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.gender
     *
     * @param gender the value for tab_emp.gender
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.email
     *
     * @return the value of tab_emp.email
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.email
     *
     * @param email the value for tab_emp.email
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tab_emp.d_id
     *
     * @return the value of tab_emp.d_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tab_emp.d_id
     *
     * @param dId the value for tab_emp.d_id
     *
     * @mbg.generated Thu Aug 29 23:27:15 CST 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}